// Code generated by MockGen. DO NOT EDIT.
// Source: internal/application/services/ai.go
//
// Generated by this command:
//
//	mockgen -source=internal/application/services/ai.go -destination=internal/mocks/mock_ai.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/EmanuelErnesto/uninaquiz-backend/internal/application/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockIAIService is a mock of IAIService interface.
type MockIAIService struct {
	ctrl     *gomock.Controller
	recorder *MockIAIServiceMockRecorder
	isgomock struct{}
}

// MockIAIServiceMockRecorder is the mock recorder for MockIAIService.
type MockIAIServiceMockRecorder struct {
	mock *MockIAIService
}

// NewMockIAIService creates a new mock instance.
func NewMockIAIService(ctrl *gomock.Controller) *MockIAIService {
	mock := &MockIAIService{ctrl: ctrl}
	mock.recorder = &MockIAIServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAIService) EXPECT() *MockIAIServiceMockRecorder {
	return m.recorder
}

// GenerateQuiz mocks base method.
func (m *MockIAIService) GenerateQuiz(ctx context.Context, topic, difficulty string) ([]dto.QuizQuestion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateQuiz", ctx, topic, difficulty)
	ret0, _ := ret[0].([]dto.QuizQuestion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateQuiz indicates an expected call of GenerateQuiz.
func (mr *MockIAIServiceMockRecorder) GenerateQuiz(ctx, topic, difficulty any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateQuiz", reflect.TypeOf((*MockIAIService)(nil).GenerateQuiz), ctx, topic, difficulty)
}
