// Code generated by MockGen. DO NOT EDIT.
// Source: internal/application/services/token.go
//
// Generated by this command:
//
//	mockgen -source=internal/application/services/token.go -destination=internal/mocks/mock_token.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockITokenService is a mock of ITokenService interface.
type MockITokenService struct {
	ctrl     *gomock.Controller
	recorder *MockITokenServiceMockRecorder
	isgomock struct{}
}

// MockITokenServiceMockRecorder is the mock recorder for MockITokenService.
type MockITokenServiceMockRecorder struct {
	mock *MockITokenService
}

// NewMockITokenService creates a new mock instance.
func NewMockITokenService(ctrl *gomock.Controller) *MockITokenService {
	mock := &MockITokenService{ctrl: ctrl}
	mock.recorder = &MockITokenServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITokenService) EXPECT() *MockITokenServiceMockRecorder {
	return m.recorder
}

// ExtractClaims mocks base method.
func (m *MockITokenService) ExtractClaims(tokenString string) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractClaims", tokenString)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExtractClaims indicates an expected call of ExtractClaims.
func (mr *MockITokenServiceMockRecorder) ExtractClaims(tokenString any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractClaims", reflect.TypeOf((*MockITokenService)(nil).ExtractClaims), tokenString)
}

// GenerateToken mocks base method.
func (m *MockITokenService) GenerateToken(userID, username string, expirationTime time.Duration) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateToken", userID, username, expirationTime)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateToken indicates an expected call of GenerateToken.
func (mr *MockITokenServiceMockRecorder) GenerateToken(userID, username, expirationTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateToken", reflect.TypeOf((*MockITokenService)(nil).GenerateToken), userID, username, expirationTime)
}

// Verify mocks base method.
func (m *MockITokenService) Verify(token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify", token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Verify indicates an expected call of Verify.
func (mr *MockITokenServiceMockRecorder) Verify(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*MockITokenService)(nil).Verify), token)
}
