// Code generated by MockGen. DO NOT EDIT.
// Source: internal/application/ports/queries.go
//
// Generated by this command:
//
//	mockgen -source=internal/application/ports/queries.go -destination=internal/mocks/mock_queries.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/EmanuelErnesto/uninaquiz-backend/internal/application/dto"
	queries "github.com/EmanuelErnesto/uninaquiz-backend/internal/application/queries"
	gomock "go.uber.org/mock/gomock"
)

// MockIGetAllUsersPort is a mock of IGetAllUsersPort interface.
type MockIGetAllUsersPort struct {
	ctrl     *gomock.Controller
	recorder *MockIGetAllUsersPortMockRecorder
	isgomock struct{}
}

// MockIGetAllUsersPortMockRecorder is the mock recorder for MockIGetAllUsersPort.
type MockIGetAllUsersPortMockRecorder struct {
	mock *MockIGetAllUsersPort
}

// NewMockIGetAllUsersPort creates a new mock instance.
func NewMockIGetAllUsersPort(ctrl *gomock.Controller) *MockIGetAllUsersPort {
	mock := &MockIGetAllUsersPort{ctrl: ctrl}
	mock.recorder = &MockIGetAllUsersPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIGetAllUsersPort) EXPECT() *MockIGetAllUsersPortMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockIGetAllUsersPort) Run(ctx context.Context, input queries.GetAllUsersQuery) (*dto.GetAllUsersResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx, input)
	ret0, _ := ret[0].(*dto.GetAllUsersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run.
func (mr *MockIGetAllUsersPortMockRecorder) Run(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockIGetAllUsersPort)(nil).Run), ctx, input)
}

// MockIGetQuizHistoryPort is a mock of IGetQuizHistoryPort interface.
type MockIGetQuizHistoryPort struct {
	ctrl     *gomock.Controller
	recorder *MockIGetQuizHistoryPortMockRecorder
	isgomock struct{}
}

// MockIGetQuizHistoryPortMockRecorder is the mock recorder for MockIGetQuizHistoryPort.
type MockIGetQuizHistoryPortMockRecorder struct {
	mock *MockIGetQuizHistoryPort
}

// NewMockIGetQuizHistoryPort creates a new mock instance.
func NewMockIGetQuizHistoryPort(ctrl *gomock.Controller) *MockIGetQuizHistoryPort {
	mock := &MockIGetQuizHistoryPort{ctrl: ctrl}
	mock.recorder = &MockIGetQuizHistoryPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIGetQuizHistoryPort) EXPECT() *MockIGetQuizHistoryPortMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockIGetQuizHistoryPort) Run(ctx context.Context, userID string) ([]dto.QuizHistoryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx, userID)
	ret0, _ := ret[0].([]dto.QuizHistoryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run.
func (mr *MockIGetQuizHistoryPortMockRecorder) Run(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockIGetQuizHistoryPort)(nil).Run), ctx, userID)
}

// MockIGetQuizPort is a mock of IGetQuizPort interface.
type MockIGetQuizPort struct {
	ctrl     *gomock.Controller
	recorder *MockIGetQuizPortMockRecorder
	isgomock struct{}
}

// MockIGetQuizPortMockRecorder is the mock recorder for MockIGetQuizPort.
type MockIGetQuizPortMockRecorder struct {
	mock *MockIGetQuizPort
}

// NewMockIGetQuizPort creates a new mock instance.
func NewMockIGetQuizPort(ctrl *gomock.Controller) *MockIGetQuizPort {
	mock := &MockIGetQuizPort{ctrl: ctrl}
	mock.recorder = &MockIGetQuizPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIGetQuizPort) EXPECT() *MockIGetQuizPortMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockIGetQuizPort) Run(ctx context.Context, quizID, userID string) (*dto.GetQuizResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx, quizID, userID)
	ret0, _ := ret[0].(*dto.GetQuizResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run.
func (mr *MockIGetQuizPortMockRecorder) Run(ctx, quizID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockIGetQuizPort)(nil).Run), ctx, quizID, userID)
}
