// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repositories/quiz.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/repositories/quiz.go -destination=internal/mocks/mock_quiz.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entities "github.com/EmanuelErnesto/uninaquiz-backend/internal/domain/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockIQuizRepository is a mock of IQuizRepository interface.
type MockIQuizRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIQuizRepositoryMockRecorder
	isgomock struct{}
}

// MockIQuizRepositoryMockRecorder is the mock recorder for MockIQuizRepository.
type MockIQuizRepositoryMockRecorder struct {
	mock *MockIQuizRepository
}

// NewMockIQuizRepository creates a new mock instance.
func NewMockIQuizRepository(ctrl *gomock.Controller) *MockIQuizRepository {
	mock := &MockIQuizRepository{ctrl: ctrl}
	mock.recorder = &MockIQuizRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIQuizRepository) EXPECT() *MockIQuizRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIQuizRepository) Create(ctx context.Context, quiz entities.Quiz) (*entities.Quiz, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, quiz)
	ret0, _ := ret[0].(*entities.Quiz)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIQuizRepositoryMockRecorder) Create(ctx, quiz any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIQuizRepository)(nil).Create), ctx, quiz)
}

// Delete mocks base method.
func (m *MockIQuizRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIQuizRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIQuizRepository)(nil).Delete), ctx, id)
}

// FindAllByUserID mocks base method.
func (m *MockIQuizRepository) FindAllByUserID(ctx context.Context, userID string) ([]entities.Quiz, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllByUserID", ctx, userID)
	ret0, _ := ret[0].([]entities.Quiz)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllByUserID indicates an expected call of FindAllByUserID.
func (mr *MockIQuizRepositoryMockRecorder) FindAllByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllByUserID", reflect.TypeOf((*MockIQuizRepository)(nil).FindAllByUserID), ctx, userID)
}

// FindByID mocks base method.
func (m *MockIQuizRepository) FindByID(ctx context.Context, id string) (*entities.Quiz, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*entities.Quiz)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockIQuizRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockIQuizRepository)(nil).FindByID), ctx, id)
}

// FindByUserTopicAndDifficulty mocks base method.
func (m *MockIQuizRepository) FindByUserTopicAndDifficulty(ctx context.Context, userID, topic, difficulty string) (*entities.Quiz, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserTopicAndDifficulty", ctx, userID, topic, difficulty)
	ret0, _ := ret[0].(*entities.Quiz)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserTopicAndDifficulty indicates an expected call of FindByUserTopicAndDifficulty.
func (mr *MockIQuizRepositoryMockRecorder) FindByUserTopicAndDifficulty(ctx, userID, topic, difficulty any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserTopicAndDifficulty", reflect.TypeOf((*MockIQuizRepository)(nil).FindByUserTopicAndDifficulty), ctx, userID, topic, difficulty)
}

// UpdateScore mocks base method.
func (m *MockIQuizRepository) UpdateScore(ctx context.Context, id string, score int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateScore", ctx, id, score)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateScore indicates an expected call of UpdateScore.
func (mr *MockIQuizRepositoryMockRecorder) UpdateScore(ctx, id, score any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateScore", reflect.TypeOf((*MockIQuizRepository)(nil).UpdateScore), ctx, id, score)
}
