// Code generated by MockGen. DO NOT EDIT.
// Source: internal/application/ports/commands.go
//
// Generated by this command:
//
//	mockgen -source=internal/application/ports/commands.go -destination=internal/mocks/mock_commands.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	commands "github.com/EmanuelErnesto/uninaquiz-backend/internal/application/commands"
	dto "github.com/EmanuelErnesto/uninaquiz-backend/internal/application/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockICreateUserPort is a mock of ICreateUserPort interface.
type MockICreateUserPort struct {
	ctrl     *gomock.Controller
	recorder *MockICreateUserPortMockRecorder
	isgomock struct{}
}

// MockICreateUserPortMockRecorder is the mock recorder for MockICreateUserPort.
type MockICreateUserPortMockRecorder struct {
	mock *MockICreateUserPort
}

// NewMockICreateUserPort creates a new mock instance.
func NewMockICreateUserPort(ctrl *gomock.Controller) *MockICreateUserPort {
	mock := &MockICreateUserPort{ctrl: ctrl}
	mock.recorder = &MockICreateUserPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICreateUserPort) EXPECT() *MockICreateUserPortMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockICreateUserPort) Run(ctx context.Context, input commands.CreateUserCommand, expirationTime time.Duration) (*dto.CreateUserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx, input, expirationTime)
	ret0, _ := ret[0].(*dto.CreateUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run.
func (mr *MockICreateUserPortMockRecorder) Run(ctx, input, expirationTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockICreateUserPort)(nil).Run), ctx, input, expirationTime)
}

// MockILoginUserPort is a mock of ILoginUserPort interface.
type MockILoginUserPort struct {
	ctrl     *gomock.Controller
	recorder *MockILoginUserPortMockRecorder
	isgomock struct{}
}

// MockILoginUserPortMockRecorder is the mock recorder for MockILoginUserPort.
type MockILoginUserPortMockRecorder struct {
	mock *MockILoginUserPort
}

// NewMockILoginUserPort creates a new mock instance.
func NewMockILoginUserPort(ctrl *gomock.Controller) *MockILoginUserPort {
	mock := &MockILoginUserPort{ctrl: ctrl}
	mock.recorder = &MockILoginUserPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockILoginUserPort) EXPECT() *MockILoginUserPortMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockILoginUserPort) Run(ctx context.Context, input commands.LoginCommand, expirationTime time.Duration) (*dto.LoginResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx, input, expirationTime)
	ret0, _ := ret[0].(*dto.LoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run.
func (mr *MockILoginUserPortMockRecorder) Run(ctx, input, expirationTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockILoginUserPort)(nil).Run), ctx, input, expirationTime)
}

// MockISaveQuizHistoryPort is a mock of ISaveQuizHistoryPort interface.
type MockISaveQuizHistoryPort struct {
	ctrl     *gomock.Controller
	recorder *MockISaveQuizHistoryPortMockRecorder
	isgomock struct{}
}

// MockISaveQuizHistoryPortMockRecorder is the mock recorder for MockISaveQuizHistoryPort.
type MockISaveQuizHistoryPortMockRecorder struct {
	mock *MockISaveQuizHistoryPort
}

// NewMockISaveQuizHistoryPort creates a new mock instance.
func NewMockISaveQuizHistoryPort(ctrl *gomock.Controller) *MockISaveQuizHistoryPort {
	mock := &MockISaveQuizHistoryPort{ctrl: ctrl}
	mock.recorder = &MockISaveQuizHistoryPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISaveQuizHistoryPort) EXPECT() *MockISaveQuizHistoryPortMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockISaveQuizHistoryPort) Run(ctx context.Context, input commands.SaveQuizHistoryCommand, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx, input, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockISaveQuizHistoryPortMockRecorder) Run(ctx, input, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockISaveQuizHistoryPort)(nil).Run), ctx, input, userID)
}

// MockIDeleteQuizHistoryPort is a mock of IDeleteQuizHistoryPort interface.
type MockIDeleteQuizHistoryPort struct {
	ctrl     *gomock.Controller
	recorder *MockIDeleteQuizHistoryPortMockRecorder
	isgomock struct{}
}

// MockIDeleteQuizHistoryPortMockRecorder is the mock recorder for MockIDeleteQuizHistoryPort.
type MockIDeleteQuizHistoryPortMockRecorder struct {
	mock *MockIDeleteQuizHistoryPort
}

// NewMockIDeleteQuizHistoryPort creates a new mock instance.
func NewMockIDeleteQuizHistoryPort(ctrl *gomock.Controller) *MockIDeleteQuizHistoryPort {
	mock := &MockIDeleteQuizHistoryPort{ctrl: ctrl}
	mock.recorder = &MockIDeleteQuizHistoryPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDeleteQuizHistoryPort) EXPECT() *MockIDeleteQuizHistoryPortMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockIDeleteQuizHistoryPort) Run(ctx context.Context, id, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockIDeleteQuizHistoryPortMockRecorder) Run(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockIDeleteQuizHistoryPort)(nil).Run), ctx, id, userID)
}

// MockIGenerateQuizPort is a mock of IGenerateQuizPort interface.
type MockIGenerateQuizPort struct {
	ctrl     *gomock.Controller
	recorder *MockIGenerateQuizPortMockRecorder
	isgomock struct{}
}

// MockIGenerateQuizPortMockRecorder is the mock recorder for MockIGenerateQuizPort.
type MockIGenerateQuizPortMockRecorder struct {
	mock *MockIGenerateQuizPort
}

// NewMockIGenerateQuizPort creates a new mock instance.
func NewMockIGenerateQuizPort(ctrl *gomock.Controller) *MockIGenerateQuizPort {
	mock := &MockIGenerateQuizPort{ctrl: ctrl}
	mock.recorder = &MockIGenerateQuizPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIGenerateQuizPort) EXPECT() *MockIGenerateQuizPortMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockIGenerateQuizPort) Run(ctx context.Context, input commands.GenerateQuizCommand, userID string) (*dto.GenerateQuizResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx, input, userID)
	ret0, _ := ret[0].(*dto.GenerateQuizResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run.
func (mr *MockIGenerateQuizPortMockRecorder) Run(ctx, input, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockIGenerateQuizPort)(nil).Run), ctx, input, userID)
}
